2018-11-25 16:10:12,094 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-25 16:11:20,338 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-25 16:11:47,800 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-25 16:12:39,286 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-25 16:13:38,002 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-25 16:20:22,475 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-25 16:23:17,594 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-27 18:37:09,230 INFO: Microblog startup [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-27 18:39:38,165 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-27 18:49:39,981 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-11-27 20:15:13,896 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-02 17:56:39,275 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-02 18:03:06,643 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-05 17:21:46,831 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-05 17:27:02,257 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-05 17:47:35,102 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-05 17:47:49,929 ERROR: Exception on /search [GET] [in /Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/evh111/Desktop/programz/petblog/app/main/routes.py", line 148, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/Users/evh111/Desktop/programz/petblog/app/models.py", line 16, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/Users/evh111/Desktop/programz/petblog/app/search.py", line 26, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 660, in search
    doc_type, '_search'), params=params, body=body)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index')
2018-12-05 17:57:36,992 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-05 17:57:41,699 ERROR: Exception on /search [GET] [in /Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/evh111/Desktop/programz/petblog/app/main/routes.py", line 148, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/Users/evh111/Desktop/programz/petblog/app/models.py", line 16, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/Users/evh111/Desktop/programz/petblog/app/search.py", line 26, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 660, in search
    doc_type, '_search'), params=params, body=body)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Users/evh111/Desktop/programz/petblog/myenv/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index')
2018-12-05 17:59:30,947 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-05 18:02:57,860 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-08 13:22:26,273 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-08 13:23:15,248 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-08 13:23:43,327 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-08 13:27:02,843 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-08 13:29:07,577 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
2018-12-10 19:21:32,202 INFO: PetBlog [in /Users/evh111/Desktop/programz/petblog/app/__init__.py:82]
